# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-02 11:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedResultsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('band_slug', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('browser_id', models.CharField(max_length=1024)),
                ('referer', models.CharField(blank=True, max_length=255, null=True)),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bands.Band')),
            ],
        ),
    ]
