#!/home/tjs/.venv/bbr4/bin/python
# (c) 2011, 2018 Tim Sawyer, All Rights Reserved

import sys, os
from datetime import datetime, timedelta

print (sys.path)
os.environ['DJANGO_SETTINGS_MODULE'] = 'bbr4.settingslive'
#os.environ['DJANGO_SETTINGS_MODULE'] = 'bbr.settings'

import django
django.setup()

from django.utils import timezone
from django.core.mail import send_mail, EmailMessage
from django.contrib.auth.models import User
from feedback.models import SiteFeedback
from users.models import UserProfile
from feedback.tasks import notification as feedback_notification

# Look through owned feedback without a claim date that is not done 
# - if it is older than 7 days, put it into the feedback queue
lFeedback = SiteFeedback.objects.filter(claim_date__isnull=True).filter(status="Outstanding")
lToday = timezone.now()
lCount = 0
lTjsUser = User.objects.filter(username='tjs')[0]
for feedback in lFeedback:
  lFeedbackSubmitted = feedback.created
  lMessage = ""
  lOwner = feedback.owner
  lWeekAgo = lToday - timedelta(days=7)
  if lFeedbackSubmitted < lWeekAgo:
      feedback.status = 'Queue'
      feedback.save("Auto moved to Feedback Queue from %s" % lOwner)
      lMessage = "MOVED TO QUEUE"
      feedback_notification.delay(None, feedback, 'feedback', 'autoqueue', lTjsUser, ('127.0.0.1','feedback_batch'), pAdditionalContext={'QueuedFrom' : lOwner})
      lCount += 1
      
  print ("%d - %s %s - %s (%s)" % (feedback.id, lFeedbackSubmitted, lOwner, feedback.status, lMessage))
print ("%d queued" % lCount)

print ("Looking for users that haven't logged in for over a year and expiring")
lDeltaDate = datetime.now() - timedelta(days=366)
lOldUsers = UserProfile.objects.filter(user__last_login__lt=lDeltaDate).exclude(user__email="expired@brassbandresults.co.uk").order_by('-user__last_login')
print (" - %d found" % len(lOldUsers))
for profile in lOldUsers:
  lExpired = str(datetime.now() - profile.user.last_login)
  lExpired = lExpired[:-15]
  print ("%s - %s" % (profile.user.username, lExpired))
  profile.new_email_required = True
  profile.user.email = "expired@brassbandresults.co.uk"
  profile.save()
  profile.user.save()


