#!/home/bbr/.venv/bbr4/bin/python
# (c) 2012, 2018 Tim Sawyer, All Rights Reserved

import sys, os, re
from datetime import datetime, timedelta

os.environ['DJANGO_SETTINGS_MODULE'] = 'bbr.settingslive'

import django
django.setup()

from django.contrib.auth.models import User
from bands.models import Band
from bbr.notification import notification

print ("Running monthly notification tasks")
lToday = datetime.today()
lOneMonthAgo = datetime.today() - timedelta(days=32)

lNewBands = Band.objects.filter(created__lte=lToday, created__gte=lOneMonthAgo)
lTjsUser = User.objects.filter(username='tjs')[0]
notification(None, lNewBands, 'bands', 'new_band', 'monthly', lTjsUser, ('',''), pAdditionalContext={'StartDate' : lOneMonthAgo, 'EndDate': lToday})