#!/home/bbr/.venv/bbr4/bin/python
# (c) 2012, 2018 Tim Sawyer, All Rights Reserved

import sys, os, re
from datetime import datetime, timedelta

os.environ['DJANGO_SETTINGS_MODULE'] = 'bbr.settingslive'

import django
django.setup()

from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.core.mail import send_mail
from bbr.notification import notification
from bands.models import Band

DESTINATIONS = [
  'monthly@brassbandresults.com',
]


print ("Running monthly notification tasks")
lToday = datetime.today()
lOneMonthAgo = datetime.today() - timedelta(days=32)

lNewBands = Band.objects.filter(created__lte=lToday, created__gte=lOneMonthAgo)

lContext = {
    'ThingNew' : lNewBands,
    'StartDate' : lOneMonthAgo,
    'EndDate' : lToday,
}

lRenderedEmail = render_to_string('bands/notify/new_band_monthly.txt', lContext)
         
lSubject = render_to_string('bands/notify/new_band_monthly_subject.txt', lContext)
lSubject = ''.join(lSubject.splitlines()) #  *must not* contain newlines


send_mail(lSubject, lRenderedEmail, 'BrassBandResults <monthly@brassbandresults.co.uk>', DESTINATIONS, fail_silently=False)
