# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-02 11:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('name', models.CharField(help_text='Current name of band', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('website_review', models.IntegerField(blank=True, choices=[(5, 'Wow'), (4, 'Good'), (3, 'Average'), (2, 'Functional'), (1, 'Rubbish'), (-1, 'None')], null=True)),
                ('twitter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, help_text='Rehearsal room postcode', max_length=10, null=True)),
                ('latitude', models.CharField(blank=True, max_length=15, null=True)),
                ('longitude', models.CharField(blank=True, max_length=15, null=True)),
                ('map_location', django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, editable=False, null=True, srid=4326)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, editable=False, geography=True, null=True, srid=4326)),
                ('rehearsal_night_1', models.CharField(blank=True, choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], max_length=2, null=True)),
                ('rehearsal_night_2', models.CharField(blank=True, choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], max_length=2, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website_news_page', models.CharField(blank=True, help_text='URL of page containing band news', max_length=200, null=True)),
                ('website_contact_page', models.CharField(blank=True, help_text='URL of page containing band contact form', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, help_text='Date band started contesting (yyyy-mm-dd)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Date band folded or merged (yyyy-mm-dd)', null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Extinct'), (1, 'Competing'), (2, 'Non-competing'), (3, 'Youth'), (4, 'Salvation Army'), (5, 'Now a Wind Band')], null=True)),
                ('national_grading', models.CharField(blank=True, max_length=20, null=True)),
                ('scratch_band', models.BooleanField(default=False)),
                ('first_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FirstParentBand', to='bands.Band')),
                ('lastChangedBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='BandLastChangedBy', to=settings.AUTH_USER_MODEL)),
                ('mapper', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BandMapper', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='BandOwner', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.Region')),
                ('second_parent', models.ForeignKey(blank=True, help_text='Used for the parents when a band merges with another', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SecondParentBand', to='bands.Band')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BandRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('left_band_name', models.CharField(blank=True, max_length=100)),
                ('relationship', models.CharField(choices=[('parent', 'Is Parent Of'), ('senior', 'Is Senior Band To'), ('subsumed', 'Was Subsumed Into'), ('split', 'Split From'), ('scratch', 'Is Scratch Band From'), ('reformed', 'Reformed As')], max_length=10)),
                ('right_band_name', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('lastChangedBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='BandRelationshipLastChangedBy', to=settings.AUTH_USER_MODEL)),
                ('left_band', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LeftBand', to='bands.Band')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='BandRelationshipOwner', to=settings.AUTH_USER_MODEL)),
                ('right_band', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RightBand', to='bands.Band')),
            ],
        ),
        migrations.CreateModel(
            name='BandTalkPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('text', models.TextField()),
                ('lastChangedBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='BandTalkPageLastChangedBy', to=settings.AUTH_USER_MODEL)),
                ('object_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Band')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='BandTalkPageOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousBandName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('old_name', models.CharField(help_text='Old band name', max_length=100)),
                ('alias_start_date', models.DateField(blank=True, help_text='Start date for this alias (yyyy-mm-dd)', null=True)),
                ('alias_end_date', models.DateField(blank=True, help_text='End date for this alias (yyyy-mm-dd)', null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Band')),
                ('lastChangedBy', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PreviousBandNameLastChangedBy', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PreviousBandNameOwner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['old_name'],
            },
        ),
    ]
