#!/bin/bash

rm -r target
mkdir -p target/build

cp -r ~/.virtualenvs/bbr-notify-twitter/lib/python3.6/site-packages/* target/build
cp *.py target/build

cd target/build
zip -r ../bbr_notify_twitter.zip *
