# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 19:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('title', models.CharField(blank=True, default='', help_text='Title, i.e. Dr or Captain.  This will appear before the name.', max_length=40)),
                ('qualifications', models.CharField(blank=True, help_text='Professional qualifications, i.e. BA (Hons).  These will appear after the name.', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('home_phone', models.CharField(blank=True, max_length=20)),
                ('mobile_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('profile', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_photos/%Y')),
                ('visible', models.BooleanField(default=False)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('lastChangedBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ClassifiedPersonLastChangedBy', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ClassifiedPersonOwner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Classified people',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('first_names', models.CharField(blank=True, max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, choices=[('Jnr', 'Jnr'), ('Snr', 'Snr'), ('I', 'I'), ('II', 'II'), ('III', 'III')], help_text='Jnr, Sr etc.', max_length=10, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bandname', models.CharField(blank=True, help_text='Band this person is most associated with.  Only populate where duplicate conductor names', max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('deceased', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, help_text="Person won't be matched with things before this date (YYYY-MM-DD)", null=True)),
                ('end_date', models.DateField(blank=True, help_text="Person won't be matched with things after this date (YYYY-MM-DD)", null=True)),
                ('old_adjudicator_id', models.IntegerField(blank=True, help_text='The serial of this person as an adjudicator', null=True)),
                ('old_conductor_id', models.IntegerField(blank=True, help_text='The serial of this person as a conductor', null=True)),
                ('old_composer_id', models.IntegerField(blank=True, help_text='The serial of this person as a composer/arranger', null=True)),
                ('old_adjudicator_slug', models.SlugField(blank=True, help_text='The slug of this person as an adjudicator', null=True)),
                ('old_conductor_slug', models.SlugField(blank=True, help_text='The slug of this person as a conductor', null=True)),
                ('old_composer_slug', models.SlugField(blank=True, help_text='The slug of this person as a composer/arranger', null=True)),
                ('combined_name', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('profile_discount_code', models.CharField(blank=True, default='', max_length=30)),
                ('lastChangedBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='PersonLastChangedBy', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='PersonOwner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['surname', 'first_names', 'slug', 'bandname'],
            },
        ),
        migrations.CreateModel(
            name='PersonAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('hidden', models.BooleanField(default=True)),
                ('lastChangedBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='PersonAliasLastChangedBy', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='PersonAliasOwner', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
            ],
            options={
                'ordering': ['name', 'person'],
            },
        ),
        migrations.CreateModel(
            name='PersonRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('relation', models.CharField(max_length=20)),
                ('reverse_relation', models.CharField(blank=True, max_length=20, null=True)),
                ('lastChangedBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='PersonRelationLastChangedBy', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='PersonRelationOwner', to=settings.AUTH_USER_MODEL)),
                ('relation_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RelationPerson', to='people.Person')),
                ('source_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SourcePerson', to='people.Person')),
            ],
        ),
        migrations.AddField(
            model_name='classifiedperson',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.Person'),
        ),
    ]
