# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 19:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('payment_date', models.DateField()),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
            options={
                'ordering': ['-payment_date', 'user_profile__user__username'],
            },
        ),
    ]
