# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 19:50
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClarificationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('comment', models.TextField()),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='SiteFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('url', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('Outstanding', 'Feedback Outstanding'), ('Done', 'Feedback Complete'), ('Queue', 'In Superuser Feedback Queue'), ('Admin', 'In Admin Feedback Queue'), ('Inconclusive', 'Not Enough Info')], default='Queue', max_length=20, null=True)),
                ('claim_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('browser_id', models.CharField(max_length=1024)),
                ('audit_log', models.TextField(blank=True, null=True)),
                ('lastChangedBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='FeedbackLastChangedBy', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='FeedbackOwner', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
