# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 19:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.CharField(blank=True, help_text='Center location for region map', max_length=15, null=True)),
                ('longitude', models.CharField(blank=True, help_text='Center location for region map', max_length=15, null=True)),
                ('default_map_zoom', models.IntegerField(blank=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, editable=False, geography=True, null=True, srid=4326)),
                ('slug', models.SlugField()),
                ('country_code', models.CharField(blank=True, max_length=20, null=True)),
                ('seed_contest_group_slug', models.CharField(blank=True, max_length=50, null=True)),
                ('container', models.ForeignKey(blank=True, help_text='Containing Region', null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.Region')),
                ('lastChangedBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='RegionLastChangedBy', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='RegionOwner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
