# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 19:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('bands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('band_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='cd_covers/%Y')),
                ('type', models.CharField(choices=[('cd', 'Purchase CD'), ('download', 'Download Track')], default='download', max_length=10)),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bands.Band')),
                ('lastChangedBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='DownloadAlbumLastChangedBy', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='DownloadAlbumOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('lastChangedBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='DownloadStoreLastChangedBy', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='DownloadStoreOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, null=True)),
                ('band_name', models.CharField(blank=True, max_length=100, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pieces.DownloadAlbum')),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bands.Band')),
                ('lastChangedBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='DownloadTrackLastChangedBy', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='DownloadTrackOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('TestPiece', 'Test Piece'), ('March', 'March'), ('Solo', 'Solo'), ('Other', 'Other')], default='TestPiece', max_length=10)),
                ('percussion_required', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('arranger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ArrangerPerson', to='people.Person')),
                ('composer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ComposerPerson', to='people.Person')),
                ('lastChangedBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='TestPieceLastChangedBy', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='TestPieceOwner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestPieceAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('lastChangedBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='TestPieceAliasLastChangedBy', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='TestPieceAliasOwner', to=settings.AUTH_USER_MODEL)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pieces.TestPiece')),
            ],
            options={
                'verbose_name_plural': 'Test piece aliases',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='downloadtrack',
            name='test_piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pieces.TestPiece'),
        ),
        migrations.AddField(
            model_name='downloadalbum',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pieces.DownloadStore'),
        ),
    ]
