#!/bin/bash

rm -r target
mkdir -p target/build

cp -r $VIRTUALENVWRAPPER_HOOK_DIR/bbr-award-points/lib/python3.6/site-packages/* target/build
cp *.py target/build
cp -r psycopg2 target/build

cd target/build
zip -r ../bbr_award_points.zip *
