# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 19:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('B', 'Band'), ('U', 'User')], default='U', max_length=1)),
                ('level', models.CharField(choices=[('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold')], default='B', max_length=1)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
